site_name: Han Doc
theme:
    name: material
    features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
repo_url: https://github.com/handemirer/handoc/
edit_uri: edit/main/docs/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences 