site_name: Han Doc
theme:
    name: material
repo_url: https://github.com/handemirer/handoc/
edit_uri: edit/main/docs/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
 
