site_name: Han Doc
theme:
    name: material
    logo: assets/logo.png
    favicon: assets/logo.png
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences